apiVersion: v1
kind: Service
metadata:
  name: landing-service
spec:
  type: ClusterIP
  selector:
    app: landing-page
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 30080
